# Generated by Django 4.2.1 on 2023-06-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentmode_app', '0002_alter_payment_options'),
        ('table_app', '0010_alter_table_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_dishname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish_app.dishmodel')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_order', models.DateField(auto_now=True)),
                ('order_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentmode_app.payment')),
                ('table', models.ForeignKey(limit_choices_to={'table_status': 'Vacant'}, on_delete=django.db.models.deletion.CASCADE, to='table_app.table')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Informations',
            },
        ),
    ]
