# Generated by Django 4.2.1 on 2023-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('Checkout', 'Checkout'), ('Pending', 'Pending')], default=('Pending', 'Pending')),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='date_order',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
