# Generated by Django 4.2.1 on 2023-06-23 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cusine_app', '0004_remove_cusine_cusine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_typename', models.CharField(max_length=255, unique=True)),
                ('dish_type_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dish Type',
                'verbose_name_plural': 'Dish Types',
            },
        ),
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dish_name', models.CharField(max_length=255, unique=True)),
                ('dish_image', models.ImageField(upload_to='uploads/')),
                ('dish_description', models.TextField(max_length=255)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cusine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusine_app.cusine')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish_app.dishtype')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
