# Generated by Django 4.2.1 on 2023-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cusine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusine_name', models.CharField(max_length=255, unique=True)),
                ('cusine_image', models.ImageField(upload_to='uploads/')),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
