# Generated by Django 4.2.1 on 2023-06-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusine_app', '0002_alter_cusine_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cusine',
            options={'verbose_name': 'Cusine', 'verbose_name_plural': 'Cusines'},
        ),
    ]
