# Generated by Django 4.2.1 on 2023-06-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='avatar',
            new_name='user_avatar',
        ),
    ]
