# Generated by Django 4.2.1 on 2023-06-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customusermodel_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
