# Generated by Django 4.2.1 on 2023-05-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('table_status', models.CharField(choices=[('0', 'Vacant'), ('1', 'Occupied')], max_length=1)),
                ('table_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
