# Generated by Django 4.2.1 on 2023-05-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[(0, 'Vacant'), (1, 'Occupied')], max_length=1),
        ),
    ]
