# Generated by Django 4.2.1 on 2023-05-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=5)),
                ('payment_mode_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
