# Generated by Django 4.2.1 on 2023-06-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmode_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment Mode', 'verbose_name_plural': 'Payment Mode'},
        ),
    ]
